import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import HeaderBar from "@/components/header/HeaderBar";
import { ThemeProvider } from '@/context/ThemeContext';
import Contact from "@/components/Contact";
import Footer from "@/components/footer/Footer";
import { AuthProvider } from "@/context/AuthContext";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
})


export const metadata: Metadata = {
  title: "Uni English Center",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head />
      <body className={`${montserrat.variable} antialiased flex flex-col min-h-screen`}>
        <ThemeProvider>
          <AuthProvider>
          <HeaderBar />
          <main className="flex-1">{children}</main>
          <Contact />
            <Footer />
            </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}